### ISSUE TITLE
App has no preview but it seems that it already fetched the page

### ISSUE THREAD

**Issue by vader-pepe** [BePsvPT/remote-browser#5]
#### Description
I just ran this on my local machine, it works perfectly. Good job there! The problem is when I run this to my VPS. When I use it, the speed indicator shows 0Kbps. But when I go to a page, let say Facebook, the header is changing. That means the app is working, but the preview isn't there.

#### Screenshots
![App has no internet connection](https://i.ibb.co/NsNJmNw/gscreenshot-2023-01-18-112133.png)

#### To Reproduce
Just run this in your VPS without any GUI.

#### Expected Result
I get a working one, the same as my local machine.

**Comment by bepsvpt** [comment]
In some situations, the `play` event will trigger before the video is ready, and you will see the error in your screenshot.

Besides, if you are using a reverse proxy to proxy the requests(e.g. Nginx), you will need a TURN server.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play
https://webrtc.org/getting-started/turn-server

**Comment by zvirot1** [comment]
Hו
Can you please give a detailed explanation of how to work with a remote browser together with a turn server in Google's cloud environment?
Do we need to set up a turn server or can we use a free turn server?
I would appreciate it if you could insert dummy values ​​into the .env.example file

**Comment by bepsvpt** [comment]
Hello @zvirot1,

> Can you please give a detailed explanation of how to work with a remote browser together with a turn server in Google's cloud environment?

To find relevant tutorials, use the keyword "turn server" in your search. For a more specific search, such as for Ubuntu OS, input "ubuntu turn server".

> Do we need to set up a turn server or can we use a free turn server?

You can utilize a free TURN server if available. If not, you'll have to set up your own TURN server.

> I would appreciate it if you could insert dummy values ​​into the .env.example file

If your TURN server is operating with the IP address "0.0.0.0" and on port "19403", your environment variables would appear as follows:

```
TURN_SERVER=0.0.0.0:19403
TURN_KEY=your-turn-server-secret-key
```
